{
 "title": "Panneaux Solaires",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pv",
    "query": {
     "query": "label_values(hoymiles_pv_current_power,port_number)"
    }
   },
   {
    "name": "sgs",
    "label": "sgs",
    "query": {
     "query": "label_values(hoymiles_sgs_voltage,serial_number)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Inverter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "sgs" },
  {
   "title": "Total Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "hoymiles_sgs_active_power{serial_number=~\"$sgs\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "Total Amperage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "hoymiles_sgs_current_amps{serial_number=~\"$sgs\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "Network Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "hoymiles_sgs_voltage{serial_number=~\"$sgs\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "hoymiles_sgs_frequency{serial_number=~\"$sgs\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hoymiles_sgs_temperature{serial_number=~\"$sgs\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hoymiles_sgs_power_factor{serial_number=~\"$sgs\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  { "title": "Solar Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "pv" },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "hoymiles_pv_current_power{port_number=~\"$pv\"}",
     "legendFormat": "{{serial_number}}-{{port_number}}"
    }
   ]
  },
  {
   "title": "Amperage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "hoymiles_pv_current_amps{port_number=~\"$pv\"}",
     "legendFormat": "{{serial_number}}-{{port_number}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "hoymiles_pv_voltage{port_number=~\"$pv\"}",
     "legendFormat": "{{serial_number}}-{{port_number}}"
    }
   ]
  }
 ]
}